/** Atomically emit one canonical Artifact V2 site as JSON and TypeScript. */

import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { serializePreparedSite, type PreparedSite } from "@pletivo/core/artifact";

export interface EmitResult {
  modulePath: string;
  jsonPath: string;
  moduleBytes: number;
}

type RenameFile = (source: string, destination: string) => Promise<void>;

let renameFile: RenameFile = fs.rename;

/** Internal fault-injection seam; this module is not a published package export. */
export function __setEmitRenameForTests(rename: RenameFile | null): void {
  renameFile = rename ?? fs.rename;
}

export async function emitArtifact(outDir: string, site: PreparedSite): Promise<EmitResult> {
  const canonical = serializePreparedSite(site);
  await fs.mkdir(outDir, { recursive: true });
  const modulePath = path.join(outDir, "pletivo-artifact.ts");
  const jsonPath = path.join(outDir, "pletivo-artifact.json");
  const nonce = `${process.pid}-${randomUUID()}`;
  const moduleTemp = `${modulePath}.${nonce}.tmp`;
  const jsonTemp = `${jsonPath}.${nonce}.tmp`;
  const moduleBackup = `${modulePath}.${nonce}.bak`;
  const jsonBackup = `${jsonPath}.${nonce}.bak`;
  let moduleBackedUp = false;
  let jsonBackedUp = false;
  let moduleInstalled = false;
  let jsonInstalled = false;

  try {
    await Promise.all([
      fs.writeFile(jsonTemp, `${canonical}\n`),
      fs.writeFile(moduleTemp, artifactModuleSource(canonical)),
    ]);
    jsonBackedUp = await moveExistingAside(jsonPath, jsonBackup);
    moduleBackedUp = await moveExistingAside(modulePath, moduleBackup);
    await renameFile(jsonTemp, jsonPath);
    jsonInstalled = true;
    await renameFile(moduleTemp, modulePath);
    moduleInstalled = true;
  } catch (error) {
    const rollbackErrors: unknown[] = [];
    if (jsonInstalled) await removeQuietly(jsonPath);
    if (moduleInstalled) await removeQuietly(modulePath);
    if (jsonBackedUp) await restoreBackup(jsonBackup, jsonPath, rollbackErrors);
    if (moduleBackedUp) await restoreBackup(moduleBackup, modulePath, rollbackErrors);
    await Promise.all([
      removeQuietly(jsonTemp),
      removeQuietly(moduleTemp),
    ]);
    if (rollbackErrors.length > 0) {
      throw new AggregateError(
        [error, ...rollbackErrors],
        "artifact emit failed and the previous output pair could not be fully restored",
      );
    }
    throw error;
  }

  await Promise.all([removeQuietly(jsonBackup), removeQuietly(moduleBackup)]);

  const encoder = new TextEncoder();
  const moduleBytes = site.artifact.modules.reduce(
    (total, module) => total + encoder.encode(module.source).byteLength,
    0,
  );
  return { modulePath, jsonPath, moduleBytes };
}

function artifactModuleSource(canonical: string): string {
  return `// Generated by \`pletivo prepare\`. Do not edit — re-run the command.
// The literal below is the same canonical Artifact V2 value as pletivo-artifact.json.
export const PREPARED = ${canonical};
export const ARTIFACT = PREPARED.artifact;
`;
}

async function moveExistingAside(file: string, backup: string): Promise<boolean> {
  try {
    await renameFile(file, backup);
    return true;
  } catch (error) {
    if (isMissingFile(error)) return false;
    throw error;
  }
}

async function restoreBackup(
  backup: string,
  file: string,
  errors: unknown[],
): Promise<void> {
  try {
    await renameFile(backup, file);
  } catch (error) {
    errors.push(new Error(
      `artifact rollback failed for ${JSON.stringify(file)}: ${error instanceof Error ? error.message : String(error)}`,
      { cause: error },
    ));
  }
}

async function removeQuietly(file: string): Promise<void> {
  try {
    await fs.unlink(file);
  } catch (error) {
    if (!isMissingFile(error)) return;
  }
}

function isMissingFile(error: unknown): boolean {
  return typeof error === "object" && error !== null && Reflect.get(error, "code") === "ENOENT";
}
