/** Write the canonical prepared site as a TypeScript module. */

import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { serializePreparedSite, type PreparedSite } from "@pletivo/core/artifact";

export interface EmitResult {
  modulePath: string;
  moduleBytes: number;
}

export async function emitArtifact(outDir: string, site: PreparedSite): Promise<EmitResult> {
  await fs.mkdir(outDir, { recursive: true });
  const modulePath = path.join(outDir, "pletivo-artifact.ts");
  const temporaryPath = `${modulePath}.${process.pid}-${randomUUID()}.tmp`;
  const source = artifactModuleSource(serializePreparedSite(site));
  try {
    await fs.writeFile(temporaryPath, source);
    await fs.rename(temporaryPath, modulePath);
  } catch (error) {
    await fs.rm(temporaryPath, { force: true });
    throw error;
  }

  const encoder = new TextEncoder();
  const moduleBytes = site.artifact.modules.reduce(
    (total, module) => total + encoder.encode(module.source).byteLength,
    0,
  );
  return { modulePath, moduleBytes };
}

function artifactModuleSource(canonical: string): string {
  return `// Generated by \`pletivo prepare\`. Do not edit — re-run the command.
export const PREPARED = ${canonical};
export const ARTIFACT = PREPARED.artifact;
`;
}
