/**
 * Writing the artifact out, in the two forms a host actually consumes it in.
 *
 * `pletivo-artifact.ts` is the one a Worker uses: the app's bundler embeds it exactly
 * as it already embeds `astro.wasm` and Tailwind's stylesheets, so there is no fetch
 * on the hot path and no new loading mechanism. `pletivo-artifact.json` is the same
 * thing for a host that ships it out of band — R2, KV, a per-request body — and it is
 * what `parsePreparedSite` reads, so the two ends cannot drift.
 */

import fs from "node:fs/promises";
import path from "node:path";
import type { PreparedSite } from "@pletivo/core/artifact";

export interface EmitResult {
  /** Absolute path of the module a bundler should import. */
  modulePath: string;
  /** Absolute path of the same thing as JSON, for a host that does not bundle it. */
  jsonPath: string;
  /** Bytes the module map will cost the isolate. The 64 MiB Loader limit is real. */
  moduleBytes: number;
}

export async function emitArtifact(outDir: string, prepared: PreparedSite): Promise<EmitResult> {
  await fs.mkdir(outDir, { recursive: true });
  const modulePath = path.join(outDir, "pletivo-artifact.ts");
  const jsonPath = path.join(outDir, "pletivo-artifact.json");

  await fs.writeFile(jsonPath, JSON.stringify(prepared, null, 2) + "\n");
  await fs.writeFile(modulePath, artifactModuleSource(prepared));

  const moduleBytes = Object.values(prepared.modules).reduce(
    (total, code) => total + Buffer.byteLength(code, "utf8"),
    0,
  );
  return { modulePath, jsonPath, moduleBytes };
}

/**
 * The generated module.
 *
 * Every value is a JSON literal — no imports, no evaluation — so a bundler can tree
 * it, a diff of two artifacts is readable, and nothing in it can fail to load.
 */
function artifactModuleSource(prepared: PreparedSite): string {
  return `// Generated by \`pletivo prepare\`. Do not edit — re-run the command.
//
// Artifact ${prepared.artifact.id}, ${Object.keys(prepared.modules).length} module(s).
import type { PreparedSite, SiteArtifact } from "@pletivo/core/artifact";

export const ARTIFACT: SiteArtifact = ${JSON.stringify(prepared.artifact, null, 2)};

export const ARTIFACT_MODULES: Record<string, string> = ${JSON.stringify(prepared.modules, null, 2)};

/** Pass this straight to \`renderPage({ artifact })\`. */
export const PREPARED: PreparedSite = { artifact: ARTIFACT, modules: ARTIFACT_MODULES };
`;
}
