/**
 * Transpiles `@pletivo/runtime` into the JavaScript a Worker Loader can take.
 *
 * The Loader accepts modules, not TypeScript, and workerd has no `eval` — so the
 * TS→JS step cannot happen at request time. It happens here, once, and the result
 * is committed as a string constant that any bundler carries into the host worker
 * unchanged. `test/runtime-modules.test.ts` re-runs this and fails when the
 * committed copy drifts from the source.
 *
 *   bun packages/workers/scripts/build-runtime.ts
 */

import path from "node:path";

const PACKAGE_DIR = path.resolve(import.meta.dir, "..");
const OUT_FILE = path.join(PACKAGE_DIR, "src/generated/runtime-modules.ts");

/**
 * Entry points, and the name each takes in the module map handed to the isolate.
 *
 * Only the Astro shim is here: it is what `internalURL` points compiled `.astro`
 * output at, and it reaches the rest of `@pletivo/runtime` through relative
 * imports the bundle pulls in. Everything else the render path needs — the router,
 * the markdown pipeline, the CSS ordering — runs in the *host* worker, where the
 * app's own bundler already compiles TypeScript.
 */
const ENTRIES: Record<string, string> = {
  "pletivo-runtime.js": "@pletivo/runtime/astro-shim",
};

/**
 * Bundle one entry point into a single self-contained module.
 *
 * `target: "node"` rather than `"browser"` so `node:async_hooks` stays an external
 * import instead of being stubbed to `{}` — workerd provides it under
 * `nodejs_compat`, and the render-tracking store needs a real one.
 */
export async function bundleRuntimeModule(entry: string): Promise<string> {
  const result = await Bun.build({
    entrypoints: [Bun.resolveSync(entry, PACKAGE_DIR)],
    target: "node",
    format: "esm",
    minify: false,
  });
  if (!result.success) {
    throw new Error(`[pletivo-workers] bundling ${entry} failed:\n${result.logs.join("\n")}`);
  }
  return result.outputs[0].text();
}

export async function generateRuntimeModules(): Promise<string> {
  const entries: string[] = [];
  for (const [name, entry] of Object.entries(ENTRIES)) {
    const code = await bundleRuntimeModule(entry);
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(code)},`);
  }
  return [
    "// Generated by scripts/build-runtime.ts. Do not edit.",
    "//",
    "// The JavaScript form of @pletivo/runtime, ready to hand to a Worker Loader.",
    "// Regenerate with: bun packages/workers/scripts/build-runtime.ts",
    "",
    "/** Module name in the Loader bundle -> its source. */",
    "export const RUNTIME_MODULES: Readonly<Record<string, string>> = {",
    ...entries,
    "};",
    "",
    "/** The module compiled `.astro` output imports, via the compiler's `internalURL`. */",
    'export const RUNTIME_MODULE_NAME = "pletivo-runtime.js";',
    "",
  ].join("\n");
}

if (import.meta.main) {
  const source = await generateRuntimeModules();
  await Bun.write(OUT_FILE, source);
  console.log(`wrote ${path.relative(process.cwd(), OUT_FILE)} (${source.length} bytes)`);
}
