/**
 * What `@pletivo/runtime` becomes inside the render isolate: one module.
 *
 * Not one module for tidiness — one module because the runtime holds process-global
 * state. `render-context.ts` owns the AsyncLocalStorage that `runWithRenderTracking`
 * opens and that `recordRenderedModule` and `pushTsxStyle` write into. Bundling the
 * Astro shim and the JSX runtime separately would give the isolate two copies of that
 * store, and a `.tsx` page's `<style>` blocks and rendered-module set would be
 * written into a store the host never reads — a page that renders fine and quietly
 * loses its CSS. The same hazard `@pletivo/runtime`'s own package.json note describes.
 *
 * `Fragment` is the one name both halves define and they are not the same function:
 * the Astro shim's honours `set:html`, the JSX one just renders children. The JSX
 * one is re-exported under an alias here and `pletivo-jsx-runtime.js` (generated by
 * `build-runtime.ts`) renames it back, so each caller gets the one it means.
 *
 * `createPaginate` is the one thing here that is not `@pletivo/runtime`. It has to
 * be: `getStaticPaths({ paginate })` runs wherever the page module runs, and that is
 * the isolate — the props it returns hold functions and can never cross back out.
 * `@pletivo/core/paginate` imports nothing but types, so it costs the bundle nothing
 * beyond itself.
 *
 * Bundled by `scripts/build-runtime.ts`. Nothing imports this at run time.
 */

export * from "@pletivo/runtime/astro-shim";
export { jsx, jsxs, jsxDEV, Fragment as jsxFragment } from "@pletivo/runtime/jsx-runtime";
export { createPaginate } from "@pletivo/core/paginate";
